name: Build AWX workflow
on:
  workflow_dispatch:
    inputs:
      AWX_BRANCH:
        description: Version number
        required: true
        default: '21.2.0'

jobs:
  build_awx:
    name: Build AWX job
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v3

      - name: push
        run: ./build.sh ${{ github.event.inputs.AWX_BRANCH }}
