name: build and push container image
on:
  workflow_dispatch:
    inputs:
      AWX_BRANCH:
        description: Version number
        required: true
        default: '21.2.0'

jobs:
  build_and_push:
    name: build and push container image
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v3

      - name: push
        run: ./build.sh ${{ github.event.inputs.AWX_BRANCH }}